language: node_js
node_js:
- 7
cache:
  directories:
  - node_modules
  - $(npm config get prefix)/bin/gulp
  - /home/travis/.nvm/versions/node/v7.2.0/lib/node_modules
  - /home/travis/.local/bin
branches:
  except:
  - master
before_install: openssl aes-256-cbc -K $encrypted_be6f45ab858f_key -iv $encrypted_be6f45ab858f_iv -in deploy_key.enc -out deploy_key -d
install:
- npm install -g gulp
- npm install
- npm update
script:
- chmod a+x deploy.sh
- ./deploy.sh
